services:
  api:
    build: .
    # fix the 'uvloop' error
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop asyncio
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  dashboard:
    build:
      context: ./dashboard
    ports:
      - "5173:5173"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://localhost:8080